[package]
name = "rs-search"
version = "0.1.0"
edition = "2021"

[profile.dev.package.autosat]
opt-level = 3

[dependencies]
autosat = "0.1.0"
serde = { version = "1.0.164", features = [ "derive" ] }
serde_json = "1.0.96"
sha256 = "1.1.3"
